AWSTemplateFormatVersion: "2010-09-09"

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.100.0.0/16

  WebSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.100.10.0/24
      VpcId: !Ref VPC

  AppSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.100.20.0/24
      VpcId: !Ref VPC

  DBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.100.30.0/24
      VpcId: !Ref VPC

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.nano
      ImageId: ami-0b38d62acce7fb76a
      KeyName: partner-demo
      SubnetId: !Ref WebSubnet

  AppServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.nano
      ImageId: ami-0b38d62acce7fb76a
      KeyName: partner-demo
      SubnetId: !Ref AppSubnet

  DBServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.nano
      ImageId: ami-0b38d62acce7fb76a
      KeyName: partner-demo
      SubnetId: !Ref DBSubnet
